name: CI

on:
  pull_request:
    branches:
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.0
    - name: unit tests
      run: go test ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.0
    - name: unit tests
      run: go build ./cmd/apisprout

  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: sha
        run: echo "::set-output name=sha::$(git describe --always --tags --dirty)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/arm64, linux/arm, linux/amd64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
